config/routes.rb
Rails.application.routes.draw do
  get 'statistics/index'

  resources :fights

  resources :fighters

  get 'main/index'

  root 'main#index'

end

app/models/fighter.rb
class Fighter < ActiveRecord::Base
  belongs_to :fight
  belongs_to :job

  has_many :skills, dependent: :destroy

  accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" , small: '200x200'}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_attachment_presence :avatar

  validates :skills, presence: { message: 'You have to add skills' }

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :description,
    presence: false

  validates :job_id,
    presence: true

  validates :email,
    presence: true,
    uniqueness: true

    validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "invalid format"

    scope :add_exp_points, -> (fighter_info, points) { fighter_info.update(exp_points: fighter_info.exp_points + points) }

    scope :remove_data, -> (fighter_id) { Fighter.where(id: fighter_id).delete_all }

    scope :count_fights, -> (count_wins, count_loses) { count_wins + count_loses }

    scope :win_percent, -> (count_wins, count_fights) { ((count_wins.to_f / count_fights.to_f) * 100).to_i }

  def self.strongest_attack(fighter_id)
    winner_attack = Result.where(winner_id: fighter_id).maximum(:winner_attack)
    loser_attack = Result.where(loser_id: fighter_id).maximum(:loser_attack)
    max_winner_attack = winner_attack.nil? ? 0 : winner_attack
    max_loser_attack = loser_attack.nil? ? 0 : loser_attack
    if max_winner_attack > max_loser_attack
      max_winner_attack
    else
      max_loser_attack
    end
  end

  def self.weakest_attack(fighter_id)
    winner_attack = Result.where(winner_id: fighter_id).minimum(:winner_attack)
    loser_attack = Result.where(loser_id: fighter_id).minimum(:loser_attack)
    min_winner_attack = winner_attack.nil? ? 0 : winner_attack
    min_loser_attack = loser_attack.nil? ? 0 : loser_attack
    if min_winner_attack < min_loser_attack
      min_winner_attack
    else
      min_loser_attack
    end
  end
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  helper_method [:strongest_skill_attack, :weakest_skill_attack]

  def new
    @fighter = Fighter.new
  end

  def show
    @fighter_info = Fighter.find_by(id: params[:id])
    @skills = Skill.where(fighter_id: params[:id])
    @count_wins = Result.where(winner_id: params[:id]).count
    @count_loses = Result.where(loser_id: params[:id]).count
    @count_fights = Fighter.count_fights(@count_wins, @count_loses)
    @win_percent = @count_wins > 0 ||  @count_fights > 0 ? Fighter.win_percent(@count_wins, @count_fights) : 0
    @strongest_attack = Fighter.strongest_attack(params[:id])
    @weakest_attack = Fighter.weakest_attack(params[:id])
  end

  def create
    @fighter = Fighter.new(fighter_params)
    if @fighter.save
      #to count skills data should have skills_attributes
      if !fighter_params[:skills_attributes].nil?
        count_skills = Skill.where(fighter_id: Fighter.last.id).count
        count_uniq_skills = Skill.select(:name).where(fighter_id: Fighter.last.id).uniq.count
        #check if amount of skills is greater than or eq 3 and less or eq than 9
        if count_skills >= 3 &&  count_skills <= 9
          #check if skill names are unique
          if count_skills == count_uniq_skills
            WelcomeMailer.welcome(@fighter).deliver
            redirect_to root_path, notice: "New fighter is ready to battle!"
          else
            Fighter.remove_data(Fighter.last.id)
            redirect_to new_fighter_path, notice: 'Your skill names have to be unique!'
          end
        else
          Fighter.remove_data(Fighter.last.id)
          redirect_to new_fighter_path, notice: 'You need at least 3 and no more than 9 skills'
        end
      else
        render :new
      end
    else
      flash.now[:notice] = 'You have to add skills'
      render :new
    end
  end


  def strongest_skill_attack(skill_id)
    winner_attack = Result.where(winner_skill_id: skill_id).maximum(:winner_attack)
    loser_attack =  Result.where(loser_skill_id: skill_id).maximum(:loser_attack)
    winner_at = winner_attack.nil? ? 0 : winner_attack
    loser_at = loser_attack.nil? ? 0 : loser_attack
    if winner_at > loser_at
      winner_at
    else
      loser_at
    end
  end

  def weakest_skill_attack(skill_id)
    winner_attack = Result.where(winner_skill_id: skill_id).minimum(:winner_attack)
    loser_attack =  Result.where(loser_skill_id: skill_id).minimum(:loser_attack)
    winner_at = winner_attack.nil? ? 0 : winner_attack
    loser_at = loser_attack.nil? ? 0 : loser_attack
    if winner_at > loser_at && loser_at != 0
      loser_at
    else
      winner_at
    end
  end

  private
  def fighter_params
    params.require(:fighter).permit(:firstname, :lastname, :avatar, :description, :email, :job_id, skills_attributes: [:id, :name, :level, :_destroy])
  end
end

app/helpers/fighters_helper.rb
module FightersHelper
end

app/views/fighters/_skill_fields.html.haml
.nested-fields.skills
  = f.input :name, label: 'Name', label_html: { style: 'margin-right: 10px; margin-bottom: 10px;' }, input_html: { style: 'margin-bottom: 10px;' }
  = f.input :level, collection: 5.downto(1), include_blank: false, label: 'Level', label_html: { style: 'margin-right: 10px; margin-left: 10px;' 'margin-bottom: 10px;' },  input_html: {style: 'margin-bottom: 10px;'}
  = link_to_remove_association "Remove Skill", f, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', style: 'margin-bottom: 10px; margin-left: 10px;'

app/views/fighters/new.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  %ul.nav.navbar-nav
    %li= link_to 'Home', root_path
    %li= link_to 'New Fight', new_fight_path
    %li= link_to 'Ranking', statistics_index_path
%body.fighter
  %div.form_padding
    %div.new_fighter
      = simple_form_for @fighter do |f|
        = f.input :firstname, label: 'Firstname'
        = f.input :lastname, label: 'Lastname'
        = f.input :job_id, collection: Job.all.order(name: :asc), include_blank: false, prompt: "Select your job"
        = f.input :email, label: 'Email'
        = f.input :avatar, label: 'Avatar', as: :file
        = f.input :description, label: 'Description (Optional)'
        %h4 Skills
        .form.form-inline
          = f.simple_fields_for :skills do |skill|
            = render 'skill_fields', f: skill
          .links
            = link_to_add_association 'Add Skill', f, :skills, class: 'btn btn-info', style: 'margin-bottom: 20px; width: 525px;'
        .actions
          = f.button :submit, class: 'btn btn-success'

app/views/fighters/show.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  %ul.nav.navbar-nav
    %li= link_to 'Home', root_path
    %li= link_to 'New Fight', new_fight_path
    %li= link_to 'Ranking', statistics_index_path
%body.fighter_page
  %h1 #{@fighter_info.firstname} #{@fighter_info.lastname}

  %div.row
    %div.col-xs-6
      %div.stats{style: 'width: 500px;'}
        %h3 Skills:
        %table.table.table-bordered{style: 'width: auto; margin-left:auto; margin-right:auto'}
          %thead
            %tr
              %th Name
              %th Level
              %th Max Attack
              %th Lowest Attack
          %tbody
            - @skills.each do |skill|
              %tr
                %td{style: 'text-align: left;'}= skill.name
                %td= skill.level
                %td= strongest_skill_attack(skill.id)
                %td= weakest_skill_attack(skill.id)
    %div.col-xs-6
      %div.stats
        %div.row.center
          %div.col-xs-6.center_stats
            %h3 Statistics:
            %div.row{style: 'width: 300px;'}
              %div.col-xs-7{style: 'text-align: left'}
                %h5 Wins:
                %h5 Loses:
                %h5 Winning percent:
                %h5 Fights played:
                %h5 Experience points:
                %h5 Strongest Attack:
                %h5 Weakest Attack:
              %div.col-xs-5
                %h5 #{@count_wins}
                %h5 #{@count_loses}
                %h5 #{@win_percent}%
                %h5 #{@count_fights}
                %h5 #{@fighter_info.exp_points}
                %h5 #{@strongest_attack}
                %h5 #{@weakest_attack}
          %div.col-xs-4.center_stats
            =image_tag @fighter_info.avatar(:small)