config/routes.rb
Rails.application.routes.draw do
  get 'statistics/index'

  resources :fights

  resources :fighters

  get 'main/index'

  root 'main#index'

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  helper_method [:count_fights, :strongest_attack, :show_job]

  def index
    @fighters = Fighter.where('exp_points > ?', 100)
  end

  private

  def count_fights(fighter_id)
    count_wins = Result.where(winner_id: fighter_id).count
    count_loses = Result.where(loser_id: fighter_id).count
    @count_fights = Fighter.count_fights(count_wins, count_loses)
  end

  def strongest_attack(fighter_id)
    count_wins = Result.where(winner_id: fighter_id).count
    count_loses = Result.where(loser_id: fighter_id).count
    @strongest_attack = Fighter.strongest_attack(fighter_id)
  end

  def show_job(job_id)
    @job = Job.where(id: job_id).first
    @job.name
  end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/index.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  %ul.nav.navbar-nav
    %li= link_to 'Home', root_path
    %li= link_to 'New Fighter', new_fighter_path
    %li= link_to 'New Fight', new_fight_path

%body.rankings
  %h1 Rankings
  %div.back_table
    %h2 The Most Fights
    %table#most_fights.table.table-bordered.dataTable
      %thead
        %tr
          %th Nr
          %th Full Name
          %th Job
          %th Experience Points
          %th Fights
          %th{ colspan: "1" }
      %tbody
        - @fighters.each do |fighter|
          %tr
            %td
            %td= fighter.firstname + ' ' + fighter.lastname
            %td= send(:show_job, fighter.job_id)
            %td= fighter.exp_points
            %td= send(:count_fights, fighter.id)
            %td= button_to 'Show Fighter', fighter_path(fighter.id), method: :get, class: 'btn btn-info btn-sm'
  %div.back_table
    %h2 The Most Powerful Attack
    %table#most_pow_attack.table.table-bordered.dataTable
      %thead
        %tr
          %th Nr
          %th Full Name
          %th Job
          %th Experience Points
          %th Strongest Attack
          %th{ colspan: "1" }
      %tbody
        - @fighters.each do |fighter|
          %tr
            %td
            %td= fighter.firstname + ' ' + fighter.lastname
            %td= send(:show_job, fighter.job_id)
            %td= fighter.exp_points
            %td= send(:strongest_attack, fighter.id)
            %td= button_to 'Show Fighter', fighter_path(fighter.id), method: :get, class: 'btn btn-info btn-sm'